blank_issues_enabled: false
contact_links:
  - name: GitHub Discussions
    url: https://github.com/themeinerlp/HelmCharts/discussions
    about: If you have questions or need help, please use our GitHub Discussions.
  
  - name: Documentation
    url: https://github.com/themeinerlp/HelmCharts#readme
    about: Check out our documentation for information about using the Helm charts.
    
  - name: Helm Chart Repository
    url: https://themeinerlp.github.io/HelmCharts/
    about: Visit our Helm chart repository to browse available charts.
