apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "bluemap.fullname" . }}
  labels:
    {{- include "bluemap.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "bluemap.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "bluemap.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "bluemap.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-ruw"
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: packs
              mountPath: /app/config/packs
            {{- include "bluemap.configmapVolumeMounts" . | nindent 12 }}
            {{- if .Values.volumeMounts }}
            {{- toYaml .Values.volumeMounts | nindent 12 }}
            {{- end }}
      initContainers:
        - name: seed-packs
          image: alpine:3.20
          command: [ "/bin/sh", "-c" ]
          args:
            - |
              set -eu
              apk add --no-cache -q curl unzip
              echo "[Seed Packs] Downloading latest BlueMap packs..."
              mkdir -p /app/config/packs
              i=1
              for url in {{- range $i, $pack := .Values.bluemap.packs }} {{ $pack }} {{- end }}; do
                echo "[Seed Packs] Downloading $url..."
                curl -fsSL "$url" -o "/app/config/packs/$(basename "$url")"
                echo "[Seed Packs] $url saved as $(basename "$url")"
                i=$((i+1))
              done
          volumeMounts:
            - name: packs
              mountPath: /app/config/packs
      volumes:
        - name: packs
          emptyDir: {}
        {{- include "bluemap.configmapVolumes" . | nindent 8 }}
        {{- if .Values.volumes }}
        {{- toYaml .Values.volumes | nindent 8 }}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
